services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo_festalab_development
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      redis: 
        condition: service_healthy
      db:
        condition: service_healthy
    ports:
      - "3001:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/demo_festalab_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle
      - node_modules:/app/node_modules
      - tmp:/app/tmp
      - packs:/app/public/packs
    env_file:
      - .env
    command: bin/dev
    restart: unless-stopped

volumes:
  gem_cache:
  db_data:
  redis_data:
  node_modules:
  tmp:
  packs: